package Hibernate;
// Generated Apr 22, 2013 6:36:57 PM by Hibernate Tools 3.2.1.GA



/**
 * Faciliteiten generated by hbm2java
 */
public class Faciliteiten  implements java.io.Serializable {


     private Integer facId;
     private String facOmschr;
     private double facEenhprijs;

    public Faciliteiten() {
    }

    public Faciliteiten(String facOmschr, double facEenhprijs) {
       this.facOmschr = facOmschr;
       this.facEenhprijs = facEenhprijs;
    }
   
    public Integer getFacId() {
        return this.facId;
    }
    
    public void setFacId(Integer facId) {
        this.facId = facId;
    }
    public String getFacOmschr() {
        return this.facOmschr;
    }
    
    public void setFacOmschr(String facOmschr) {
        this.facOmschr = facOmschr;
    }
    public double getFacEenhprijs() {
        return this.facEenhprijs;
    }
    
    public void setFacEenhprijs(double facEenhprijs) {
        this.facEenhprijs = facEenhprijs;
    }




}


