package Hibernate;
// Generated Apr 22, 2013 6:36:57 PM by Hibernate Tools 3.2.1.GA



/**
 * Podia generated by hbm2java
 */
public class Podia  implements java.io.Serializable {


     private Integer podId;
     private String podOmschr;
     private String podLocatie;

    public Podia() {
    }

    public Podia(String podOmschr, String podLocatie) {
       this.podOmschr = podOmschr;
       this.podLocatie = podLocatie;
    }
   
    public Integer getPodId() {
        return this.podId;
    }
    
    public void setPodId(Integer podId) {
        this.podId = podId;
    }
    public String getPodOmschr() {
        return this.podOmschr;
    }
    
    public void setPodOmschr(String podOmschr) {
        this.podOmschr = podOmschr;
    }
    public String getPodLocatie() {
        return this.podLocatie;
    }
    
    public void setPodLocatie(String podLocatie) {
        this.podLocatie = podLocatie;
    }




}


