package Hibernate;
// Generated Apr 22, 2013 6:36:57 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Tickets generated by hbm2java
 */
public class Tickets  implements java.io.Serializable {


     private TicketsId id;
     private Festivals festivals;
     private int typId;
     private Date ticketDatum;

    public Tickets() {
    }

    public Tickets(TicketsId id, Festivals festivals, int typId, Date ticketDatum) {
       this.id = id;
       this.festivals = festivals;
       this.typId = typId;
       this.ticketDatum = ticketDatum;
    }
   
    public TicketsId getId() {
        return this.id;
    }
    
    public void setId(TicketsId id) {
        this.id = id;
    }
    public Festivals getFestivals() {
        return this.festivals;
    }
    
    public void setFestivals(Festivals festivals) {
        this.festivals = festivals;
    }
    public int getTypId() {
        return this.typId;
    }
    
    public void setTypId(int typId) {
        this.typId = typId;
    }
    public Date getTicketDatum() {
        return this.ticketDatum;
    }
    
    public void setTicketDatum(Date ticketDatum) {
        this.ticketDatum = ticketDatum;
    }




}


